#!/bin/bash
# Build QuitOnClose.app (universal when the x86_64 SDK slice is available),
# ad-hoc sign it, and optionally install it to /Applications.
#
#   ./build.sh            build only  -> build/QuitOnClose.app
#   ./build.sh --install  build, then replace /Applications/QuitOnClose.app
set -euo pipefail

NAME="QuitOnClose"
BUNDLE_ID="com.quitonclose.app"
DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD="$DIR/build"
APP="$BUILD/$NAME.app"
MACOS="$APP/Contents/MacOS"

FRAMEWORKS=(-framework Cocoa -framework ApplicationServices -framework ServiceManagement -framework CoreAudio)
SOURCES=("$DIR"/Sources/*.swift)

rm -rf "$APP"
mkdir -p "$MACOS" "$APP/Contents/Resources"

build_slice() {
    local arch="$1" out="$2"
    swiftc -O -target "${arch}-apple-macos13.0" -o "$out" "${SOURCES[@]}" "${FRAMEWORKS[@]}" 2>/dev/null
}

echo "==> compiling arm64"
build_slice arm64 "$BUILD/$NAME.arm64"

if build_slice x86_64 "$BUILD/$NAME.x86_64"; then
    echo "==> compiling x86_64 (universal build)"
    lipo -create "$BUILD/$NAME.arm64" "$BUILD/$NAME.x86_64" -output "$MACOS/$NAME"
    rm -f "$BUILD/$NAME.x86_64"
else
    echo "==> x86_64 SDK slice unavailable, shipping arm64 only"
    mv "$BUILD/$NAME.arm64" "$MACOS/$NAME"
fi
rm -f "$BUILD/$NAME.arm64"

# App icon. Assets/AppIcon.icns is generated by scripts/make-icon.swift and
# committed, so a plain build needs no extra tooling; it is only rebuilt when
# the generator or the shared drawing code is newer than the icon.
ICNS="$DIR/Assets/AppIcon.icns"
if [[ ! -f "$ICNS" \
      || "$DIR/scripts/make-icon.swift" -nt "$ICNS" \
      || "$DIR/Sources/MenuBarIcon.swift" -nt "$ICNS" ]]; then
    echo "==> regenerating app icon"
    swiftc -O "$DIR/scripts/make-icon.swift" "$DIR/Sources/MenuBarIcon.swift" -o "$BUILD/make-icon"
    (cd "$DIR" && "$BUILD/make-icon" >/dev/null)
fi
cp "$ICNS" "$APP/Contents/Resources/AppIcon.icns"

cp "$DIR/Info.plist" "$APP/Contents/Info.plist"
printf 'APPL????' > "$APP/Contents/PkgInfo"

# Ad-hoc signature with a stable identifier. Accessibility (TCC) keys off the
# code signature, so a rebuild can ask for the permission again.
codesign --force --sign - --identifier "$BUNDLE_ID" "$APP"
codesign --verify --verbose=1 "$APP"

echo "==> built $APP"
lipo -archs "$MACOS/$NAME"

if [[ "${1:-}" == "--install" ]]; then
    stage=$(mktemp -d "/Applications/.QuitOnClose-install.XXXXXX")
    cp -R "$APP" "$stage/$NAME.app"
    codesign --verify --deep --strict "$stage/$NAME.app"
    # Old installations used a KeepAlive LaunchAgent as well as Open at Login.
    # Stop it before replacing the executable, otherwise it restarts mid-copy
    # and creates a second independent menu. Preserve the plist for rollback.
    legacy="$HOME/Library/LaunchAgents/com.robert.quitonclose.plist"
    migrated_login=false
    legacy_was_loaded=false
    legacy_backup=""
    rollback_install() {
        trap - ERR
        if [[ -d "$stage/previous.app" ]]; then
            if [[ -d "/Applications/$NAME.app" ]]; then mv "/Applications/$NAME.app" "$stage/failed.app"; fi
            mv "$stage/previous.app" "/Applications/$NAME.app"
        fi
        if [[ -n "$legacy_backup" && -f "$legacy_backup" ]]; then mv "$legacy_backup" "$legacy"; fi
        if [[ "$legacy_was_loaded" == true ]]; then
            launchctl bootstrap "gui/$(id -u)" "$legacy"
        elif [[ -d "/Applications/$NAME.app" ]]; then
            open "/Applications/$NAME.app"
        fi
        exit 1
    }
    trap rollback_install ERR
    if [[ -f "$legacy" ]]; then
        if launchctl print "gui/$(id -u)/com.robert.quitonclose" >/dev/null 2>&1; then
            legacy_was_loaded=true
            launchctl bootout "gui/$(id -u)/com.robert.quitonclose"
        fi
        legacy_backup="${legacy}.disabled-$(date +%Y%m%d%H%M%S)"
        mv "$legacy" "$legacy_backup"
        migrated_login=true
    fi
    "$MACOS/$NAME" --stop-existing
    if [[ -d "/Applications/$NAME.app" ]]; then
        mv "/Applications/$NAME.app" "$stage/previous.app"
    fi
    mv "$stage/$NAME.app" "/Applications/$NAME.app"
    echo "==> installed /Applications/$NAME.app"
    if [[ "$migrated_login" == true ]]; then
        "/Applications/$NAME.app/Contents/MacOS/$NAME" --register-login
    fi
    open "/Applications/$NAME.app"
    trap - ERR
fi
